kind: project
metadata:
  name: text-classification-bert
  created: '2023-10-24T12:09:28.970227'
spec:
  functions:
  - url: preprocess.py
    name: pre-processing
    kind: job
    image: mlrun/mlrun
    handler: preprocessdata
  - url: evaluate.py
    name: evaluate
    kind: job
    image: mlrun/mlrun
    handler: start_evaluate
  - url: train.py
    name: train
    kind: job
    image: mlrun/mlrun
    handler: start_train