kind: project
metadata:
  name: text-classification-fasttext3
  created: '2024-01-23T13:47:58.767232'
spec:
  functions:
  - url: 01-preprocessing_handlers.py
    name: pre-processing
    kind: job
    image: mlrun/mlrun
    handler: parse_ipzs
  - url: 02-parsing_handlers.py
    name: parsing
    kind: job
    image: ertomaselli/classification-parsing:latest
    handler: parse
  - url: 03-extracting_test_handlers.py
    name: extracting_test
    kind: job
    image: mlrun/mlrun
    handler: extract_test_sets
  - url: 04-saving_data_handlers.py
    name: saving_data
    kind: job
    image: ertomaselli/classification-parsing:latest
    handler: save_data
  - url: 05-filtering_handlers.py
    name: filtering
    kind: job
    image: ertomaselli/classification-parsing:latest
    handler: filter
  - url: training_handlers.py
    name: training
    kind: job
    image: ertomaselli/classification-training:latest
    handler: train
  - url: 06-evaluation_handlers.py
    name: evaluation
    kind: job
    image: mlrun/mlrun
    handler: evaluate
  - name: model-server
    spec:
      kind: serving
      metadata:
        name: model-server
        project: text-classification-fasttext3
        categories: []
      spec:
        command: ''
        args: []
        image: ertomaselli/classification-tqdm-stanza-fasttext:latest
        build:
          commands: []
          code_origin: git://github.com/etomaselli/mlrun-document-classification.git#refs/heads/main
          requirements: []
        description: ''
        disable_auto_mount: false
        clone_target_dir: ''
        env: []
        preemption_mode: prevent
        min_replicas: 1
        max_replicas: 4
        source: ''
        function_kind: serving_v2
        base_image_pull: false
        graph:
          kind: router
          after: []
          routes:
            allTokens_unfiltered_model:
              kind: task
              class_name: model_serving.ClassifierModel
              class_args:
                model_path: ./allTokens_unfiltered_model.bin
              after: []
        secret_sources: []
        affinity: null
        tolerations: null
        security_context: {}
      verbose: false
  - url: 03-extracting_test_handlers.py
    name: extracting-test
    kind: job
    image: mlrun/mlrun
    handler: extract_test_sets
  - url: 04-saving_data_handlers.py
    name: saving-data
    kind: job
    image: ertomaselli/classification-parsing:latest
    handler: save_data
  workflows:
  - engine: kfp
    path: classification_pipeline.py
    name: classification
    handler: classification_pipeline
  artifacts: []
  conda: ''
  source: git://github.com/etomaselli/mlrun-document-classification.git#refs/heads/main
  origin_url: git://github.com/etomaselli/mlrun-document-classification.git#refs/heads/main
  desired_state: online
  build:
    commands: []
    requirements: []
  custom_packagers: []
status:
  state: online
